### ISSUE TITLE
Support v13?

### ISSUE THREAD

**Issue by Cobertos** [alexanderrobertson/emoji-extractor#1]
Looks like there's a full list for v13, https://unicode.org/emoji/charts-13.0/full-emoji-list.html

Any chance this will get updated?

**Comment by alexanderrobertson** [comment]
Ah yes! I'll get this done this week. Sorry for the delay - I didn't get a notification about this issue.

**Comment by alexanderrobertson** [comment]
This is now updated to v13.0. You can upgrade with `pip install emoji-extractor --upgrade`.

**Comment by Cobertos** [comment]
Sweet, thank you so much!
