### ISSUE TITLE
Python 3.10 Support: Use `collections.abc` instead of `collections`

### ISSUE THREAD

**Issue by wongsingfo** [alexanderrobertson/emoji-extractor#2]
Below is the error message:

```py
  File "C:\Users\....\AppData\Local\Programs\Python\Python310\lib\site-packages\emoji_extractor\extract.py", line 4, in <module>
    from collections import Counter, Iterable
ImportError: cannot import name 'Iterable' from 'collections' (C:\Users\....\AppData\Local\Programs\Python\Python310\lib\collections\__init__.py)
```

Previously, collections.abc was available from the collections import. In Python 3.10, they were explicitly moved to collections.abc. As such, any references to collections abstract base classes need to import collections.abc in Python 3.10.

**Comment by alexanderrobertson** [comment]
Thanks for letting me know! Have updated this along with the addition of Unicode 14.0.
